field: cb9fa8ca-2e1d-4f19-9fdb-fbc0048c48ac # Team Members
fieldLayouts:
  36b1e08f-2a1c-4628-9a2a-a460142a62c3:
    tabs:
      -
        elements:
          -
            fieldUid: 5f9d7235-34f1-4e35-b869-2aab91ba74cd # Photo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0012468e-69ca-40ef-a774-9026ae855095 # MemberName
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e220bc0-756f-41f2-84c4-5ccf9c362438 # Member Designation
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5f9d7235-34f1-4e35-b869-2aab91ba74cd: # Photo
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: ''
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:70526dc9-81b4-4ef6-916c-509abbde8927' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add a photo'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:70526dc9-81b4-4ef6-916c-509abbde8927' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:70526dc9-81b4-4ef6-916c-509abbde8927' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8e220bc0-756f-41f2-84c4-5ccf9c362438: # Member Designation
    contentColumnType: text
    fieldGroup: null
    handle: memberDesignation
    instructions: ''
    name: 'Member Designation'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0012468e-69ca-40ef-a774-9026ae855095: # MemberName
    contentColumnType: text
    fieldGroup: null
    handle: membername
    instructions: ''
    name: MemberName
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: teamMembers
name: 'Team Members'
sortOrder: 1
