fieldLayouts:
  9091d4e4-3abf-4cfd-b734-b9e6a5a4d28f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: cd45df90-8dac-4388-bdfd-9ea6197eaf54 # D7 Purpose
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5fe91cd9-a3d8-421f-bed6-981143919b5e # D7 Committment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf943240-ffbd-4ce2-8692-197370d370c0 # D7 Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 152ede2a-5a24-4a93-b883-7ca9723b61b4 # D7 Services Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c84dc50-c742-4c23-b98a-1002a52470ad # D7 Best Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e950ba82-dc33-4a4b-84fb-ee975fc832fd # D7 Top Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 389116b0-c40c-45a6-8ac1-051c7cdcff20 # D7 Portfolios
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4374ce41-eaf8-4399-9b19-6bff6b04c012 # D7 Case Study
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6cba3503-534a-4330-9bee-a76c5f9fdc3e # D7 Strategy Planing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f12b8e3-b2de-496b-86c6-381458efa890 # D7 Strategy Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: afa68825-2534-4f3d-9874-6e8bcb17bbde # D7 Service Title 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a10b996-7638-49e4-b56f-9637ea5526a3 # D7 Service Title 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03df2faf-1747-4bce-a1d9-1888b33955b7 # D7 Service Title 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f91d641-d87f-4e02-8acd-882c5966ad58 # D7 Service Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 64004947-6347-4db4-a7b0-fb30271df817 # Recent News Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03c08aac-4323-4851-8b6a-e6c8ee2dded0 # Recent Blog Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b24ce5b-e429-4ef5-b7f8-ca6125ea5a15 # More About Us
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 49809cbb-d3ee-4b81-9308-3824c1415635 # Our Members Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ada6b2dd-f586-47ef-b86a-c2199acaed73 # Support Company Area
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1619a362-b53b-4fb8-b439-bf44858d086f # Support Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f82d0af-f24f-4fe4-974c-8685d851cb96 # More About Us 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4aba7c3d-d9e0-4a63-b84f-9924cfbec115 # Search 4 Consultant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Content 2'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 9613c6c6-1a1a-4aa2-83c9-737fe8957c1d # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48139ded-7ade-4bc8-8041-3f5212a9af19 # Counter Up
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cb9fa8ca-2e1d-4f19-9fdb-fbc0048c48ac # Team Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 25903487-0e0d-453f-85b6-e376ace9d037 # Recent News
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a99dec1-26e3-4c89-aedd-2e1559ad9db5 # Our Top Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 94e9c477-d4a0-4078-a7e3-6a31bc34940b # Brands
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Repeating Content'
        sortOrder: 3
handle: home
hasTitleField: true
name: Home
section: adca758e-1875-4716-b45d-c3537284bf28 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
