contentColumnType: text
fieldGroup: bc8a07c5-f961-4aea-8e6c-beffb9886774 # Blog Page
handle: postContent
instructions: ''
name: 'Post Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 70526dc9-81b4-4ef6-916c-509abbde8927 # Uploads
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
