fieldLayouts:
  f3c3d170-1cf9-4438-89c7-edb91c025b9e:
    tabs:
      -
        elements:
          -
            fieldUid: 0ed04be5-d855-4e79-9701-668b10e08357 # Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: header
name: Header
