enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  3668c9ca-7f11-49e8-8702-8bc3cf6da0e4: # Desevens Digital
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
