enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  3668c9ca-7f11-49e8-8702-8bc3cf6da0e4: # Desevens Digital
    enabledByDefault: true
    hasUrls: true
    template: services
    uriFormat: services
type: single
